module RickyIpsum
  class << self
    QUOTES = [
      "ME ESTA AGARRANDO OTRA ULCERA. NO PUEDO VERLO MAS.....",
      "YO NO PUEDO CREER LO QUE VEO....",
      "CHICOS NO SE PREOCUPEN SI HAY DEFAULT CON EL NUEVO PRESIDENTE YO PAGO LA CUENTA Y NOS VAMOS TODOS A MIAMI DE JODA",
      "VOY A REÍR... VOY A GOZAR... VIVIR MI VIDA... LA LA LA LA !!!!!. YENDO O LLENDO DA IGUAL PORQUE VOY ARRIBA DE MI ROLLs ROYCE. BASTA CHICOS.",
      "AHI TENE!!!! LA FORBES HABLANDO DE MI!!!! TOMA PA VO!!! JAJAJA... AHORA SI HABLEN CON MOTIVO LOS RESENTIDOS ...JAJA QUE SE QUEDE CON SUS MARTÍN FIERRO TRUCHOS QUE EL RECONOCIMIENTO DE FORBES ES MÁS IMPORTANTE Y CREÍBLE.. ES MÁS IMPORTANTE Y CREÍBLE... EL BOLUDO, CLARO SIN SABER,  JUSTO LLAMA A UN PRENSA EN MIAMI AMIGO MÍO..LLAMAR PARA AVISAR QUE VIENE CON LA OLGA KARINA..TODO POR LA FOTITO MMMMMM,VIERON COMO HABLANDO SE PUEDE EXPRESAR DOS PENSAMIENTOS DIFERENTES SIN LLEGAR A LA AGRESIÓN .. JAJAJA CAFÉ FASHION...ACÁ SE HABLA DE TODO.. MAMAAAAAA!!! .",
      "UNA VERGÜENZA Y UN INSULTO AL TELEVIDENTE. NO SE SOPORTA VERLO Y OÍR LOS DIÁLOGOS PAUPERRIMOS FALTOS DE ACTORES. AMPLIARE EN MI COLUNA..",
      "LA VIDA ES UN BANQUETE Y ESTAS RATAS ESTÁN MUERTAS DE HAMBRE Y LES MOLESTA QUE YO DISFRUTE MI VIDA Y ELLAS NO PUEDAN. SIGAN HABLANDO DE MI..",
      "PASE POR LA PUERTA DE C5N CON MI ROLLS ROYCE RUMBO A UNA CENA Y SIN QUERER ATROPELLE ALGO. NO SE SI FUE UNA RATA O FUE BABY. SERÁ EL? Q MAL!.",
      "SE CAYO EL MOVIL.. ME FUI....",
      "MIAMEEEEEEEEEEEEEE.",
      "MAMA! SACA LA MANO DE AHI CARAJO.",
      "SI QUERES TE ENSEÑO A MAQUILLARTE PORQUE TE MAQUILLAS MUY MAL.",
      "CAMBIE DE IDEA... MI REGALO DE CUMPLEAÑOS... CORVETTE STINGRAY....",
      "ALGUIEN LE PUEDE DECIR EL PAPEL LAMENTABLE QUE ESTA HACIENDO??",
      "NO AGUANTO ESCUCHAR TANTO PELOTUDO Y TANTA PELOTUDA JUNTA.. MEJOR APAGO LA TELE....",
      "NA NA NA NA... SE LE FUERON LOS PERROS A LA MIERDA!!!!! JAJAJAJA CUANTA HIPOCRESÍA POR DIOS!!"
    ]

    def text(quantity = 1, separator = "\n")
      QUOTES.sample(quantity).join(separator)
    end
  end
end
